vim.opt.autoindent = true
vim.opt.copyindent = true
vim.opt.autoread = true
vim.opt.autowriteall = true
vim.opt.backup = false
vim.opt.breakindent = true
vim.opt.clipboard = "unnamedplus"
vim.opt.cmdheight = 1
vim.opt.completeopt = {"menuone", "noselect"}
vim.opt.conceallevel = 1
vim.opt.confirm = true
vim.opt.cursorline = true
vim.opt.cursorlineopt = "number,screenline"
vim.opt.expandtab = true
vim.opt.nrformats = "bin,hex,alpha"
-- Folding
vim.opt.foldclose = ""
vim.opt.foldcolumn = "auto"
vim.opt.foldenable = true
vim.opt.foldlevelstart = 99
vim.opt.foldmethod = "syntax"
vim.opt.foldopen = "insert,jump,mark,percent,search" 
-- searching options
vim.opt.hlsearch = true
vim.opt.ignorecase = true
-- Mouse behaviour
vim.opt.mouse = "a"
vim.opt.mousehide = true
-- Line numbering
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.pumblend = 10
vim.opt.pumheight = 10
vim.opt.scrolloff = 999
vim.opt.shiftround = true
vim.opt.shiftwidth = 2
vim.opt.showmatch = true
vim.opt.matchtime = 1
vim.opt.showmode = true
vim.opt.showtabline = 1
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.spell = true
vim.opt.spelloptions="camel"
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.termguicolors = true
vim.opt.undofile = true
vim.opt.signcolumn = "auto"
vim.opt.statusline = "%-t[%-M%-R]%-y%=line:%l/%L(%p)[col:%v]%=%{FugitiveStatusline()}"
